name: CallAdmin
main: org.calladmin.main
version: 0.7
api-version: 1.14
prefix:
commands:
  calladmin:
    description: Report a player or an issue
    usage: /calladmin <player> <reason>
  cainfo:
    description: Display the plugin info
    usage: /cainfo
  caresolve:
    description: Resolve the report
    usage: /caresolve <player> <reason>      
permissions:
  calladmin.exempt:
    description: Protects players from being reported
    default: op
  calladmin.notify:
    description: Allows to get update alerts
    default: op
  calladmin.admin:
    description: Admin override
    default: op